# Generated by Django 2.0.1 on 2018-01-27 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='special_notes',
            field=models.CharField(default=(), max_length=300),
            preserve_default=False,
        ),
    ]
