# Generated by Django 2.0.1 on 2018-01-27 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_special_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='special_notes',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
