# Generated by Django 2.0.1 on 2018-01-30 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180127_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user',
            new_name='user_id',
        ),
    ]
