# Generated by Django 2.0.1 on 2018-02-04 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20180201_0118'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.CharField(default='', max_length=30),
        ),
    ]
