# Generated by Django 2.0.1 on 2018-02-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_product_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=30)),
                ('descripcion_tag', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name_tag', 'descripcion_tag'),
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('id', 'user_id', 'order_status')},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_tag',
        ),
        migrations.AddField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(default=None, to='api.Tag'),
        ),
    ]
