# Generated by Django 2.0.1 on 2018-02-05 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180205_0330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('user_id', 'id')},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id', 'name_product', 'name_brand')},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('id', 'name_tag')},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(default=None, to='api.Tag', verbose_name='list of sites'),
        ),
    ]
