# Generated by Django 2.0.1 on 2018-02-05 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20180205_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_tag',
            field=models.ManyToManyField(default=None, to='api.Tag', verbose_name='list of tags'),
        ),
    ]
