# Generated by Django 2.0.1 on 2018-02-09 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Address'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shopping_cart_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ShoppingCart'),
        ),
    ]
