# Generated by Django 2.0.1 on 2018-02-09 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20180209_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(default='United State', max_length=30),
        ),
    ]
