# Generated by Django 2.0.1 on 2018-02-10 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20180209_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'ordering': ('id', 'user_id')},
        ),
    ]
