# Generated by Django 2.0.1 on 2018-02-13 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180213_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('user', 'id')},
        ),
    ]
