# Generated by Django 2.0.1 on 2018-02-13 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20180213_0021'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ('street_name', 'id', 'user')},
        ),
    ]
