# Generated by Django 2.0.1 on 2018-02-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20180213_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url_image_product',
            field=models.CharField(default='./static/noimage.png', max_length=300),
        ),
    ]
