# Generated by Django 2.0.1 on 2018-02-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_product_url_image_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url_image_product',
            field=models.CharField(default='http://via.placeholder.com/300x300', max_length=300),
        ),
    ]
